//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountApprovedLevel
    {
        public int accountApprovedID { get; set; }
        public string accountApprovedLevel1 { get; set; }
    }
}
