//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app
    {
        public int appID { get; set; }
        public string appName { get; set; }
        public string appIconLocation { get; set; }
        public string appURL { get; set; }
        public string appMiniDescription { get; set; }
        public int appLocked { get; set; }
    }
}
