//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C32_inches
    {
        public long C32_inchesId { get; set; }
        public string C32_fraction { get; set; }
        public decimal C32_decimal { get; set; }
    }
}
