//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyRep
    {
        public long repId { get; set; }
        public string rep_firstName { get; set; }
        public string rep_lastName { get; set; }
        public string rep_cellNum { get; set; }
        public string rep_email { get; set; }
        public string loginToken { get; set; }
    }
}
