//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyRepProfile
    {
        public int companyRepProfileId { get; set; }
        public string companyRepPassword { get; set; }
        public int repId { get; set; }
        public Nullable<System.DateTime> lastAuthentication { get; set; }
        public int tokenExpirationDays { get; set; }
    }
}
