//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNRmanageEntities : DbContext
    {
        public DNRmanageEntities()
            : base("name=DNRmanageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C16_inches> C16_inches { get; set; }
        public DbSet<C32_inches> C32_inches { get; set; }
        public DbSet<companyRepProfile> companyRepProfiles { get; set; }
        public DbSet<companyRep> companyReps { get; set; }
        public DbSet<cutter_type> cutter_type { get; set; }
        public DbSet<cutter> cutters { get; set; }
        public DbSet<part_drift_sizes> part_drift_sizes { get; set; }
        public DbSet<part_drill_sizes> part_drill_sizes { get; set; }
        public DbSet<part_inner_diameter> part_inner_diameter { get; set; }
        public DbSet<part_outer_diameter> part_outer_diameter { get; set; }
        public DbSet<part_style> part_style { get; set; }
        public DbSet<part_threads> part_threads { get; set; }
        public DbSet<part> parts { get; set; }
        public DbSet<parts_cutter_junction> parts_cutter_junction { get; set; }
        public DbSet<repair> repairs { get; set; }
        public DbSet<request_status> request_status { get; set; }
        public DbSet<request> requests { get; set; }
        public DbSet<state> states { get; set; }
        public DbSet<stockPoint> stockPoints { get; set; }
        public DbSet<tool_status> tool_status { get; set; }
        public DbSet<tool_type> tool_type { get; set; }
        public DbSet<tool> tools { get; set; }
    }
}
