//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class part
    {
        public long partId { get; set; }
        public Nullable<int> tooltypeId { get; set; }
        public Nullable<int> drill_sizeId { get; set; }
        public Nullable<int> drift_sizeId { get; set; }
        public Nullable<int> threadId { get; set; }
        public Nullable<int> inner_diameterId { get; set; }
        public Nullable<int> outer_diameterId { get; set; }
        public Nullable<int> styleId { get; set; }
    }
}
