//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class part_drill_sizes
    {
        public long drill_sizeId { get; set; }
        public string drill_size_fractional_inches { get; set; }
        public decimal drill_size_decimal_inches { get; set; }
    }
}
