//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class part_outer_diameter
    {
        public int outer_diameterId { get; set; }
        public Nullable<decimal> outer_diameter_decimal_inches { get; set; }
        public string outer_diameter_fractional_inches { get; set; }
    }
}
