//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdpNew
    {
        public int sdpNewsID { get; set; }
        public string newsTitle { get; set; }
        public Nullable<System.DateTime> news_date { get; set; }
        public string newsAuthor { get; set; }
        public string newsText { get; set; }
        public int displayforEveryone { get; set; }
        public int userID { get; set; }
    }
}
