//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdpUsersEntities : DbContext
    {
        public sdpUsersEntities()
            : base("name=sdpUsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountApprovedLevel> accountApprovedLevels { get; set; }
        public DbSet<app> apps { get; set; }
        public DbSet<employedBy> employedBies { get; set; }
        public DbSet<sdpNew> sdpNews { get; set; }
        public DbSet<userProfile> userProfiles { get; set; }
        public DbSet<usersAppsSelection> usersAppsSelections { get; set; }
        public DbSet<websiteNew> websiteNews { get; set; }
    }
}
