//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockPoint
    {
        public long stockPointId { get; set; }
        public string stock_city { get; set; }
        public Nullable<long> stock_stateId { get; set; }
        public string stock_address1 { get; set; }
        public string stock_address2 { get; set; }
        public string stock_zip { get; set; }
        public string stock_name { get; set; }
    }
}
