//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tool
    {
        public long toolId { get; set; }
        public string serial { get; set; }
        public Nullable<int> partId { get; set; }
        public Nullable<long> tool_statusId { get; set; }
        public Nullable<long> stockPointId { get; set; }
        public Nullable<long> in_transitId { get; set; }
        public Nullable<decimal> length1 { get; set; }
        public Nullable<decimal> length2 { get; set; }
        public Nullable<decimal> length3 { get; set; }
        public Nullable<decimal> length4 { get; set; }
        public Nullable<decimal> length5 { get; set; }
        public Nullable<decimal> length_total { get; set; }
        public Nullable<decimal> top_Od_decimal { get; set; }
        public Nullable<decimal> mid_Od_decimal { get; set; }
        public Nullable<decimal> bottom_Od_decimal { get; set; }
        public string top_Od_fractional_inches { get; set; }
        public string mid_Od_fractional_inches { get; set; }
        public string bottom_Od_fractional_inches { get; set; }
        public Nullable<long> sdp_toolId { get; set; }
    }
}
