//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersAppsSelection
    {
        public int usersAppID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> appID { get; set; }
    }
}
