//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userProfile
    {
        public int webuserID { get; set; }
        public Nullable<int> accountApproved { get; set; }
        public Nullable<int> showNews { get; set; }
        public int showAlert { get; set; }
        public int employedbyID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string alias { get; set; }
        public Nullable<System.DateTime> dateAccountCreated { get; set; }
        public Nullable<System.DateTime> lastLoggedIn { get; set; }
        public string IPAddress { get; set; }
        public string IPAddress2 { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> regionID { get; set; }
        public int p_adminsystem { get; set; }
        public int p_bittracker { get; set; }
        public int p_bitrepairmodification { get; set; }
        public int p_sdfinventoryPatron { get; set; }
        public int p_sdpinventoryCompany { get; set; }
        public int p_bittracker_all { get; set; }
        public int P_bitracker_adamk { get; set; }
        public int p_bittracker_alaska { get; set; }
        public int p_nozzlestore { get; set; }
    }
}
