//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brain.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class websiteNew
    {
        public int websiteNewsID { get; set; }
        public string articleTitle { get; set; }
        public Nullable<System.DateTime> articleDate { get; set; }
        public string articleAuthor { get; set; }
        public string articleText { get; set; }
        public string articlePicURL { get; set; }
        public int displayOnSite { get; set; }
    }
}
